# Generated by Django 4.1.13 on 2025-08-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDetails',
        ),
    ]
