# Generated by Django 4.1.13 on 2025-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_application', '0004_login_delete_clientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
