# Generated by Django 4.1.13 on 2025-08-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_application', '0005_client_details_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_categories',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('photo_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'event_categories',
            },
        ),
        migrations.AlterModelOptions(
            name='client_details',
            options={'managed': False},
        ),
    ]
